### Importação dos dados

In [2]:
import pandas as pd

In [9]:
df = pd.read_csv("customer_shopping_data.csv", parse_dates = ['invoice_date'], sep=",")

In [31]:
print("Primeiras linhas")
df.head(30)

Primeiras linhas

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
5,I227836,C657758,Female,28,Clothing,5,1500.40,Credit Card,24/05/2022,Forum Istanbul
6,I121056,C151197,Female,49,Cosmetics,1,40.66,Cash,13/03/2022,Istinye Park
7,I293112,C176086,Female,32,Clothing,2,600.16,Credit Card,13/01/2021,Mall of Istanbul
8,I293455,C159642,Male,69,Clothing,3,900.24,Credit Card,4/11/2021,Metrocity
9,I326945,C283361,Female,60,Clothing,2,600.16,Credit Card,22/08/2021,Kanyon
10,I306368,C240286,Female,36,Food & Beverage,2,10.46,Cash,25/12/2022,Metrocity
11,I139207,C191708,Female,29,Books,1,15.15,Credit Card,28/10/2022,Emaar Square Mall
12,I640508,C225330,Female,67,Toys,4,143.36,Debit Card,31/07/2022,Metrocity
13,I179802,C312861,Male,25,Clothing,2,600.16,Cash,17/11/2022,Cevahir AVM
14,I336189,C555402,Female,67,Clothing,2,600.16,Credit Card,3/6/2022,Kanyon
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,7/11/2021,Viaport Outlet
16,I294687,C300786,Male,65,Books,2,30.30,Debit Card,16/01/2021,Metrocity
17,I195744,C330667,Female,42,Food & Beverage,3,15.69,Credit Card,5/1/2022,Zorlu Center
18,I993048,C218149,Female,46,Clothing,2,600.16,Cash,26/07/2021,Metropol AVM
19,I992454,C196845,Male,24,Toys,4,143.36,Cash,7/3/2023,Cevahir AVM
20,I183746,C220180,Male,23,Clothing,1,300.08,Credit Card,15/02/2023,Emaar Square Mall
21,I412481,C125696,Female,27,Food & Beverage,1,5.23,Cash,1/5/2021,Cevahir AVM
22,I823067,C322947,Male,52,Clothing,2,600.16,Credit Card,18/06/2022,Cevahir AVM
23,I252275,C313348,Male,44,Technology,5,5250.00,Cash,26/10/2021,Kanyon
24,I174250,C204553,Female,42,Books,5,75.75,Cash,16/12/2022,Metrocity
25,I195396,C285161,Male,51,Toys,2,71.68,Debit Card,16/05/2021,Istinye Park
26,I196704,C289625,Female,25,Cosmetics,5,203.30,Credit Card,20/04/2022,Mall of Istanbul
27,I217053,C192344,Male,50,Shoes,4,2400.68,Cash,10/10/2022,Emaar Square Mall
28,I655874,C447138,Female,65,Shoes,3,1800.51,Cash,23/08/2022,Cevahir AVM
29,I209744,C251229,Male,29,Cosmetics,3,121.98,Credit Card,29/04/2021,Istinye Park

###### Tamanho da base

In [13]:
print("tamano de linhas e colunas")
df.shape

tamano de linhas e colunas

(99457, 10)

###### Identificando colunas

In [11]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='str')

###### Tipos de dados

In [10]:
print("Nomes das colunas e os tipos de dados")
print("como o 'invoice_date' está em str, será necessario mudar para data.\n")
df.info()

Nomes das colunas e os tipos de dados
como o 'invoice_date' está em str, será necessario mudar para data.

<class 'pandas.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  str
 1   customer_id     99457 non-null  str
 2   gender          99457 non-null  str
 3   age             99457 non-null  int64
 4   category        99457 non-null  str
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  str
 8   invoice_date    99457 non-null  str
 9   shopping_mall   99457 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 7.6 MB

###### Resumo estatístico

In [14]:
print("Estastistícas:")

df.describe()

Estastistícas:

                age      quantity         price
count  99457.000000  99457.000000  99457.000000
mean      43.427089      3.003429    689.256321
std       14.990054      1.413025    941.184567
min       18.000000      1.000000      5.230000
25%       30.000000      2.000000     45.450000
50%       43.000000      3.000000    203.300000
75%       56.000000      4.000000   1200.320000
max       69.000000      5.000000   5250.000000

###### Valores Únicos por coluna:

In [24]:
print("valores não nulos ")
df.nunique()

valores não nulos

invoice_no        99457
customer_id       99457
gender                2
age                  52
category              8
quantity              5
price                40
payment_method        3
invoice_date        797
shopping_mall        10
dtype: int64